#!/bin/sh

# Startup script for ldd.
# Author: Trapti Damodar Balgi

case "$1" in
    start)
        echo "ldd - loading scull driver, faulty driver & running modprobe"
        /usr/bin/module_load faulty
        /usr/bin/scull_load
        modprobe hello
        ;;
    stop)
        echo "ldd - unloading scull driver, faulty driver & removing modprobe"
        /usr/bin/module_unload faulty
        /usr/bin/scull_unload
        rmmod hello
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0